### ISSUE TITLE
Question: Can I use this in non expo app?

### ISSUE THREAD

**Issue by levani** [expo/expo-pixi#30]
I'm not using expo in my app. Can I still use this library?

**Comment by EvanBacon** [comment]
[x-post](https://github.com/expo/expo-three/issues/43)
No, this library is very high level. Just off the top it requires GLView, Asset, Font, & FileSystem.
You will need to add Expo to your RN project. The easiest way to do this is to create a new expo project and copy your code over to it. In order to get this library running I had to add native code to a bunch of different libs. This would be pretty hard to replicate outside of Expo.
