### ISSUE TITLE
Doesn't work with React-Native 0.57.5

### ISSUE THREAD

**Issue by flybayer** [expo/expo-pixi#44]
expo-gl works after upgrading to React-Native 0.57.5 but expo-pixi does not.

You can reproduce with the pixi branch of this sample project: https://github.com/flybayer/TestExpoGL/tree/pixi 

The latest commit on that branch upgrades React-Native and breaks expo-pixi. You can see this by checking out an earlier commit.

**Comment by 0xClpz** [comment]
It also breaks expo 31

**Comment by hwaterke** [comment]
It breaks on the latest version of expo.
The reason is that `expo-pixi` depends on `expo-asset` 1.0.0 and the latest version of expo uses `expo-asset` 1.1.1

When both versions are loaded, it is impossible to use expo/vector-icon in the app.

**Comment by EvanBacon** [comment]
@0xClpz fixed this. Live in `expo-pixi@0.3.2`

**Comment by flybayer** [comment]
@EvanBacon I really appreciate you working on this, but it's still not working with expo-pixi `0.3.2` and expo `31.0.5`. I updated the sample project that shows this:

https://github.com/flybayer/TestExpoGL/tree/pixi

**Comment by 0xClpz** [comment]
MMhhh that's weird it worked for me in expo 31.0.2

**Comment by EvanBacon** [comment]
@flybayer have you tried using other GL things outside of expo. I'm struggling to find signs that this is related to expo-pixi. Also in your branch, be sure to update the podfile to ios 10 as we dropped support for 9.

**Comment by alminde** [comment]
I was trying to use `expo-pixi` with https://github.com/expo/sdk-31-with-hooks-experimental (RN 0.57.4 with hooks enabled). For some reason `performance.now()` returns an object instead of a number, which made `PIXI.ticker` never update.

Installing `performance-now` from NPM and putting this:

```
import now from 'performance-now'
global.performance.now = now
```

before importing `expo-pixi` made it work for me.

I also added `global.navigator.userAgent = ''` to get rid of the CSS console output. Dunno yet if that’ll break anything else.

**Comment by flybayer** [comment]
@EvanBacon can this be reopened, so it doesn't get lost? As I last commented, I verified it's an issue with expo-pixi specifically.
